# T81-558: Applications of Deep Neural Networks
* Instructor: [Jeff Heaton](https://sites.wustl.edu/jeffheaton/), School of Engineering and Applied Science, [Washington University in St. Louis](https://engineering.wustl.edu/Programs/Pages/default.aspx)
* For more information visit the [class website](https://sites.wustl.edu/jeffheaton/t81-558/).

**Module 10 Assignment: Time Series Neural Network**

**Student Name: Jason Walker**

# Assignment Instructions

For this assignment you will use a LSTM to predict a time series contained in the data file **[series-31-spring-2018.csv](https://github.com/jeffheaton/t81_558_deep_learning/blob/master/data/series-31-spring-2018.csv)**.  The code that you will use to complete this will be similar to the sunspots example from the course module.  This data set contains two columns: *time* and *value*.  Create a LSTM network and train it with a sequence size of 5 and a prediction window of 1.  If you use a different sequence size, you will not have the correct number of submission rows. Train the neural network, the data set is fairly simple and you should easily be able to get a RMSE below 1.0.  FYI, I generate this datasets by fitting a cubic spline to a series of random points. 

This is a time series data set, do not randomize the order of the rows!  For your training data use all *time* values less than 3000 and for test, use the remaining values greater than or equal to 3000. For the submit file, send me the results of your test evaluation.  You should have two columns: *time* and *value*.  The column *time* should be the time at the beginning of each predicted sequence. The *value* should be the next value that was predicted for each of your sequences.

Your submission file will look similar to:

# Helpful Functions

You will see these at the top of every module and assignment.  These are simply a set of reusable functions that we will make use of.  Each of them will be explained as the semester progresses.  They are explained in greater detail as the course progresses.  Class 4 contains a complete overview of these functions.

In [1]:
from sklearn import preprocessing
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import shutil
import os
import requests
import base64


# Encode text values to dummy variables(i.e. [1,0,0],[0,1,0],[0,0,1] for red,green,blue)
def encode_text_dummy(df, name):
    dummies = pd.get_dummies(df[name])
    for x in dummies.columns:
        dummy_name = "{}-{}".format(name, x)
        df[dummy_name] = dummies[x]
    df.drop(name, axis=1, inplace=True)


# Encode text values to a single dummy variable.  The new columns (which do not replace the old) will have a 1
# at every location where the original column (name) matches each of the target_values.  One column is added for
# each target value.
def encode_text_single_dummy(df, name, target_values):
    for tv in target_values:
        l = list(df[name].astype(str))
        l = [1 if str(x) == str(tv) else 0 for x in l]
        name2 = "{}-{}".format(name, tv)
        df[name2] = l


# Encode text values to indexes(i.e. [1],[2],[3] for red,green,blue).
def encode_text_index(df, name):
    le = preprocessing.LabelEncoder()
    df[name] = le.fit_transform(df[name])
    return le.classes_


# Encode a numeric column as zscores
def encode_numeric_zscore(df, name, mean=None, sd=None):
    if mean is None:
        mean = df[name].mean()

    if sd is None:
        sd = df[name].std()

    df[name] = (df[name] - mean) / sd


# Convert all missing values in the specified column to the median
def missing_median(df, name):
    med = df[name].median()
    df[name] = df[name].fillna(med)


# Convert all missing values in the specified column to the default
def missing_default(df, name, default_value):
    df[name] = df[name].fillna(default_value)


# Convert a Pandas dataframe to the x,y inputs that TensorFlow needs
def to_xy(df, target):
    result = []
    for x in df.columns:
        if x != target:
            result.append(x)
    # find out the type of the target column.  Is it really this hard? :(
    target_type = df[target].dtypes
    target_type = target_type[0] if hasattr(target_type, '__iter__') else target_type
    # Encode to int for classification, float otherwise. TensorFlow likes 32 bits.
    if target_type in (np.int64, np.int32):
        # Classification
        dummies = pd.get_dummies(df[target])
        return df.as_matrix(result).astype(np.float32), dummies.as_matrix().astype(np.float32)
    else:
        # Regression
        return df.as_matrix(result).astype(np.float32), df.as_matrix([target]).astype(np.float32)

# Nicely formatted time string
def hms_string(sec_elapsed):
    h = int(sec_elapsed / (60 * 60))
    m = int((sec_elapsed % (60 * 60)) / 60)
    s = sec_elapsed % 60
    return "{}:{:>02}:{:>05.2f}".format(h, m, s)


# Regression chart.
def chart_regression(pred,y,sort=True):
    t = pd.DataFrame({'pred' : pred, 'y' : y.flatten()})
    if sort:
        t.sort_values(by=['y'],inplace=True)
    a = plt.plot(t['y'].tolist(),label='expected')
    b = plt.plot(t['pred'].tolist(),label='prediction')
    plt.ylabel('output')
    plt.legend()
    plt.show()

# Remove all rows where the specified column is +/- sd standard deviations
def remove_outliers(df, name, sd):
    drop_rows = df.index[(np.abs(df[name] - df[name].mean()) >= (sd * df[name].std()))]
    df.drop(drop_rows, axis=0, inplace=True)


# Encode a column to a range between normalized_low and normalized_high.
def encode_numeric_range(df, name, normalized_low=-1, normalized_high=1,
                         data_low=None, data_high=None):
    if data_low is None:
        data_low = min(df[name])
        data_high = max(df[name])

    df[name] = ((df[name] - data_low) / (data_high - data_low)) \
               * (normalized_high - normalized_low) + normalized_low
        
# This function submits an assignment.  You can submit an assignment as much as you like, only the final
# submission counts.  The paramaters are as follows:
# data - Pandas dataframe output.
# key - Your student key that was emailed to you.
# no - The assignment class number, should be 1 through 1.
# source_file - The full path to your Python or IPYNB file.  This must have "_class1" as part of its name.  
# .             The number must match your assignment number.  For example "_class2" for class assignment #2.
def submit(data,key,no,source_file=None):
    if source_file is None and '__file__' not in globals(): raise Exception('Must specify a filename when a Jupyter notebook.')
    if source_file is None: source_file = __file__
    suffix = '_class{}'.format(no)
    if suffix not in source_file: raise Exception('{} must be part of the filename.'.format(suffix))
    with open(source_file, "rb") as image_file:
        encoded_python = base64.b64encode(image_file.read()).decode('ascii')
    ext = os.path.splitext(source_file)[-1].lower()
    if ext not in ['.ipynb','.py']: raise Exception("Source file is {} must be .py or .ipynb".format(ext))
    r = requests.post("https://api.heatonresearch.com/assignment-submit",
        headers={'x-api-key':key}, json={'csv':base64.b64encode(data.to_csv(index=False).encode('ascii')).decode("ascii"),
        'assignment': no, 'ext':ext, 'py':encoded_python})
    if r.status_code == 200:
        print("Success: {}".format(r.text))
    else: print("Failure: {}".format(r.text))

# Assignment #10 Sample Code

The following code provides a starting point for this assignment.

In [5]:
import numpy as np
def to_sequences(seq_size, obs):
    x = []
    y = []

    for i in range(len(obs)-SEQUENCE_SIZE-1):
        #print(i)
        window = obs[i:(i+SEQUENCE_SIZE)]
        after_window = obs[i+SEQUENCE_SIZE]
        window = [[x] for x in window]
        #print("{} - {}".format(window,after_window))
        x.append(window)
        y.append(after_window)
        
    return np.array(x),np.array(y)
    

# This is your student key that I emailed to you at the beginnning of the semester.
key = "UjhQvgInJx71GabltZtqy6O1LdzxtjcE5idLxF3K"

# You must also identify your source file.  (modify for your local setup)
# file='/resources/t81_558_deep_learning/assignment_yourname_class1.ipynb'  # IBM Data Science Workbench
# file='C:\\Users\\jeffh\\projects\\t81_558_deep_learning\\t81_558_class1_intro_python.ipynb'  # Windows
file='/Users/jwalker/git/t81_558_deep_learning/assignments/assignment_jwalker_class10.ipynb'  # Mac/Linux

# Read from time series file
path = "../data/"
filename = os.path.join(path,"series-31-spring-2018.csv")    
df = pd.read_csv(filename) 

print("Starting file:")
print(df[0:10])

print("Ending file:")
print(df[-10:])

df_train = df[df['time']<3000]
df_test = df[df['time']>=3000]

value_train = df_train['value'].tolist()
value_test = df_test['value'].tolist()
print("Training set has {} observations.".format(len(value_train)))
print("Test set has {} observations.".format(len(value_test)))

Starting file:
   time      value
0     0  10.000000
1     1  10.050953
2     2  10.101758
3     3  10.152415
4     4  10.202924
5     5  10.253286
6     6  10.303499
7     7  10.353566
8     8  10.403485
9     9  10.453256
Ending file:
      time      value
3990  3990  14.694572
3991  3991  14.727313
3992  3992  14.760351
3993  3993  14.793687
3994  3994  14.827322
3995  3995  14.861256
3996  3996  14.895491
3997  3997  14.930026
3998  3998  14.964862
3999  3999  15.000000
Training set has 3000 observations.
Test set has 1000 observations.

In [6]:
import numpy as np

def to_sequences(seq_size, obs):
    x = []
    y = []

    for i in range(len(obs)-SEQUENCE_SIZE-1):
        #print(i)
        window = obs[i:(i+SEQUENCE_SIZE)]
        after_window = obs[i+SEQUENCE_SIZE]
        window = [[x] for x in window]
        #print("{} - {}".format(window,after_window))
        x.append(window)
        y.append(after_window)
        
    return np.array(x),np.array(y)
    
    
SEQUENCE_SIZE = 5
x_train,y_train = to_sequences(SEQUENCE_SIZE,value_train)
x_test,y_test = to_sequences(SEQUENCE_SIZE,value_test)

print("Shape of training set: {}".format(x_train.shape))
print("Shape of test set: {}".format(x_test.shape))

Shape of training set: (2994, 5, 1)
Shape of test set: (994, 5, 1)

In [7]:
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM
from keras.datasets import imdb
from keras.callbacks import EarlyStopping
import numpy as np

print('Build model...')
model = Sequential()
model.add(LSTM(64, dropout=0.0, recurrent_dropout=0.0,input_shape=(None, 1)))
model.add(Dense(32))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=5, verbose=1, mode='auto')
print('Train...')

model.fit(x_train,y_train,validation_data=(x_test,y_test),callbacks=[monitor],verbose=2,epochs=1000)

Using TensorFlow backend.
/Users/jwalker/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)

Build model...
Train...
Train on 2994 samples, validate on 994 samples
Epoch 1/1000
 - 2s - loss: 75.6515 - val_loss: 18.8075
Epoch 2/1000
 - 1s - loss: 0.5388 - val_loss: 0.4816
Epoch 3/1000
 - 1s - loss: 0.0240 - val_loss: 0.1388
Epoch 4/1000
 - 1s - loss: 0.0095 - val_loss: 0.0754
Epoch 5/1000
 - 1s - loss: 0.0050 - val_loss: 0.0454
Epoch 6/1000
 - 1s - loss: 0.0034 - val_loss: 0.0469
Epoch 7/1000
 - 1s - loss: 0.0033 - val_loss: 0.0381
Epoch 8/1000
 - 1s - loss: 0.0022 - val_loss: 0.0286
Epoch 9/1000
 - 1s - loss: 0.0019 - val_loss: 0.0261
Epoch 10/1000
 - 1s - loss: 0.0017 - val_loss: 0.0178
Epoch 11/1000
 - 1s - loss: 0.0045 - val_loss: 0.0202
Epoch 12/1000
 - 1s - loss: 0.0027 - val_loss: 0.0329
Epoch 13/1000
 - 1s - loss: 0.0014 - val_loss: 0.0226
Epoch 14/1000
 - 1s - loss: 0.0015 - val_loss: 0.0225
Epoch 15/1000
 - 1s - loss: 0.0016 - val_loss: 0.0199
Epoch 00015: early stopping

In [8]:
from sklearn import metrics

pred = model.predict(x_test)
score = np.sqrt(metrics.mean_squared_error(pred,y_test))
print("Score (RMSE): {}".format(score))

Score (RMSE): 0.1409649671715266

In [79]:
dfSubmit = pd.DataFrame({'time':time_list[0:len(pred)], 'value':pred[:,0]})
display(dfSubmit)

     time      value
0    3000  36.453144
1    3001  36.460079
2    3002  36.466862
3    3003  36.473488
4    3004  36.479954
5    3005  36.486271
6    3006  36.492432
7    3007  36.498440
8    3008  36.504269
9    3009  36.509953
10   3010  36.515484
11   3011  36.520870
12   3012  36.526112
13   3013  36.531204
14   3014  36.536160
15   3015  36.540966
16   3016  36.545631
17   3017  36.550159
18   3018  36.554543
19   3019  36.558788
20   3020  36.562893
21   3021  36.566864
22   3022  36.570698
23   3023  36.574390
24   3024  36.577957
25   3025  36.581379
26   3026  36.584644
27   3027  36.587742
28   3028  36.590725
29   3029  36.593571
..    ...        ...
964  3964  14.051321
965  3965  14.077656
966  3966  14.104278
967  3967  14.131189
968  3968  14.158390
969  3969  14.185882
970  3970  14.213664
971  3971  14.241741
972  3972  14.270108
973  3973  14.298778
974  3974  14.327757
975  3975  14.357033
976  3976  14.386603
977  3977  14.416471
978  3978  14.446640
979  3979  14.477108
980  3980  14.507872
981  3981  14.538937
982  3982  14.570305
983  3983  14.601967
984  3984  14.633927
985  3985  14.666191
986  3986  14.698758
987  3987  14.731630
988  3988  14.764807
989  3989  14.798289
990  3990  14.832081
991  3991  14.866179
992  3992  14.900580
993  3993  14.935286

[994 rows x 2 columns]

In [80]:
# Submit this assignment
submit(source_file=file,data=dfSubmit,key=key,no=10)

Success: Submitted Assignment #10 for walker-jason:
You have submitted this assignment 2 times. (this is fine)
Warning: The mean of column value differs from the solution file by 0.012438246421890398. (might not matter if small)